language: node_js
node_js:
  - 8
services:
  - docker
script:
  - NODE_ENV=test npm test
after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < coverate/lcov.info
  - if [ -n "$TRAVIS_TAG" ]; then
    docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    docker build -t $DOCKER_REPO:latest .
    docker tag $DOCKER_REPO:$TRAVIS_COMMIT
    docker tag $DOCKER_REPO:$TRAVIS_TAG
    docker push $DOCKER_REPO
    fi
